apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymongo
spec:
  selector:
    matchLabels:
      app: mymongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mymongo
    spec:
      containers:
      - name: mymongo
        image: giltayar/mymongo
        ports:
        - containerPort: 27017
